### ISSUE TITLE
Missing key-value of Torchreid config file after switching to FaceNet

### ISSUE THREAD

**Issue by rathaROG** [rathaumons/pyppbox#21]
Missing key-value for key `device` e.g. `device: cuda` of the internal Torchreid config file after setting FaceNet.

```
>>> import pyppbox
>>> pyppbox.launchGUI()
RCFGTorchreid : set() -> 'device'
Traceback (most recent call last):
  File "C:\dev\exc\python\p311\Lib\site-packages\pyppbox\config\myconfig.py", line 882, in set
    self.device = self.configs['device']
                  ~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\exc\python\p311\Lib\site-packages\pyppbox\config\myconfig.py", line 1390, in setAllRCFG
    self.rcfg_torchreid.set(d)
  File "C:\dev\exc\python\p311\Lib\site-packages\pyppbox\config\myconfig.py", line 893, in set
    raise ValueError(msg)
ValueError: RCFGTorchreid : set() -> 'device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\exc\python\p311\Lib\site-packages\pyppbox\gui\ui_launcher.py", line 462, in <module>
    ui.setupUi(launcher)
  File "C:\dev\exc\python\p311\Lib\site-packages\pyppbox\gui\ui_launcher.py", line 225, in setupUi
    self.cfgMapper()
  File "C:\dev\exc\python\p311\Lib\site-packages\pyppbox\gui\ui_launcher.py", line 263, in cfgMapper
    self.mycfg.setAllRCFG()
  File "C:\dev\exc\python\p311\Lib\site-packages\pyppbox\config\myconfig.py", line 1397, in setAllRCFG
    raise ValueError("MyConfigurator : setAllRCFG() -> "  + str(e))
ValueError: MyConfigurator : setAllRCFG() -> RCFGTorchreid : set() -> 'device'
```

**Comment by rathaROG** [comment]
It can be fixed by adding `"device": self.device` after this line  https://github.com/rathaumons/pyppbox/blob/698d705b843b21f4a4b9760076cdaf63949d2da5/pyppbox/config/myconfig.py#L912
